name: lbw-donate
recipe: drupal8
config:
  webroot: web
  drush: composer
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
services:
  appserver:
    build:
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -sf /app/drush/lbw.aliases.drushrc.php ~/.drush/site-aliases/lbw.drushrc.php"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {
              "Behat\\MinkExtension" :
                {"base_url" : "http://lbw-donate.lndo.site/"},
              "Drupal\\DrupalExtension" :
                {"drush" : {"root":  "/app/web" }}
            }}
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
